name: maintenant
description: A new Flutter project.
publish_to: 'none' # empêche la publication sur pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0         # ←une seule ligne Intl
  sembast: ^3.1.0
  sembast_web: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
